version: 2

project_name: ddev-explain

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  - repository:
      owner: dkd-dobberkau
      name: homebrew-tap
    directory: Formula
    homepage: "https://github.com/dkd-dobberkau/ddev-explain"
    description: "CLI tool that summarizes DDEV project configurations"
    license: "MIT"
    install: |
      bin.install "ddev-explain"
    test: |
      system "#{bin}/ddev-explain", "--help"
